spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/tiny_task
    username: tiny_task
    password: demo123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        lob:
          non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false


logging:
  level:
    com.coyoapp.tinytask: DEBUG

#appication parameters
app:
  params:
    baseUrl: http://localhost:8080
    security:
      ui-client: coyo_client
      ui-secret: $2a$10$Yx3wNJnXw8dv7B7mSvgw7uKbzI4wKbzIsOMBtwF3mU5S7JHgxiXwS
    application:
      description: Coyo backend
      version: 0.0.1-SNAPSHOT

